---
- name: Install firewalld packages
  yum: state=present name={{ item }}
  loop:
  - firewalld-filesystem
  - firewalld

- name: Enable firewalld service
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Add specific zones to firewall
  firewalld: 
    zone: "{{ item.name }}"
    state: present
    permanent: yes
  notify: reload firewalld
  loop: "{{ fwlld_zones }}"

- name: Add firewalld services to zones
  firewalld: 
    zone: "{{ item.0.name }}"
    service: "{{ item.1 }}"
    state: enabled
    permanent: yes
  notify: reload firewalld
  with_subelements:
    - "{{ fwlld_zones | default([]) }}"
    - services 
    - skip_missing: true

- name: Add firewalld ports to zones
  firewalld: 
    zone: "{{ item.0.name }}"
    port: "{{ item.1 }}"
    state: enabled
    permanent: yes
  notify: reload firewalld
  with_subelements:
    - "{{ fwlld_zones | default([]) }}"
    - ports 
    - skip_missing: true

- name: Add firewalld sources to zones
  firewalld: 
    zone: "{{ item.0.name }}"
    source: "{{ item.1 }}"
    state: enabled
    permanent: yes
  notify: reload firewalld
  with_subelements:
    - "{{ fwlld_zones | default([]) }}"
    - sources
    - skip_missing: true


- name: Remove firewalld services from zones
  firewalld: 
    zone: "{{ item.0.name }}"
    service: "{{ item.1 }}"
    state: disabled
    permanent: yes
  notify: reload firewalld
  with_subelements:
    - "{{ fwlld_zones | default([]) }}"
    - remove_services
    - skip_missing: true

- name: Remove firewalld ports from zones
  firewalld: 
    zone: "{{ item.0.name }}"
    port: "{{ item.1 }}"
    state: disabled
    permanent: yes
  notify: reload firewalld
  with_subelements:
    - "{{ fwlld_zones | default([]) }}"
    - remove_ports 
    - skip_missing: true

- name: Remove firewalld sources from zones
  firewalld: 
    zone: "{{ item.0.name }}"
    source: "{{ item.1 }}"
    state: disabled
    permanent: yes
  notify: reload firewalld
  with_subelements:
    - "{{ fwlld_zones | default([]) }}"
    - remove_sources
    - skip_missing: true

